# Generated by Django 4.2.23 on 2025-07-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='upload_date',
        ),
    ]
