# Generated by Django 4.2.23 on 2025-07-30 12:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_document_options_remove_document_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст отзыва'),
        ),
    ]
